name: harvey.lebsack
description: 24/7
version: 0.0.1
author: yrylnlat.zjw6wly0@byi89lri.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: harveylebsack
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2025-02-18 21:53:15'
pipelines:
  pipelines/deletedOnLeftModifiedOnRightSelectLeft:
    name: deletedOnLeftModifiedOnRightSelectLeft
    description: Really solid info
    author: yrylnlat.zjw6wly0@byi89lri.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-18 21:53:15'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/deletedOnLeftModifiedOnRightSelectRight:
    name: deletedOnLeftModifiedOnRightSelectRight
    description: Really solid info
    author: yrylnlat.zjw6wly0@byi89lri.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-18 21:53:15'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/deletedOnRightModifiedOnLeftSelectLeft:
    name: deletedOnRightModifiedOnLeftSelectLeft
    description: Really solid info
    author: yrylnlat.zjw6wly0@byi89lri.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-18 21:53:16'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/deletedOnRightModifiedOnLeftSelectRight:
    name: deletedOnRightModifiedOnLeftSelectRight
    description: Really solid info
    author: yrylnlat.zjw6wly0@byi89lri.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-18 21:53:16'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/unModifiedPipeline:
    name: unModifiedPipeline
    description: Really solid info
    author: yrylnlat.zjw6wly0@byi89lri.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-18 21:53:16'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-02-18 21:53:15'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlOrchestratorPipelines: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-02-18T21:53:15.684538Z'
  name: plibMaven
  version: 8.9.0-SNAPSHOT
  id: '1786054258'
  createdAt: '2025-02-18T21:53:15.684538Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
